version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: wanderlust-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - ./backend/data/sample_posts.json:/docker-entrypoint-initdb.d/sample_posts.json:ro
      - ./backend/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro
    environment:
      MONGO_INITDB_DATABASE: wanderlust
   
  backend:
    build: ./backend
    container_name: wanderlust-backend
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    env_file:
      - ./backend/.env

  frontend:
    build: ./frontend
    container_name: wanderlust-frontend
    ports:
      - "5173:5173"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend

volumes:
  mongo-data:
